### ISSUE TITLE
is not released, isn't it?

### ISSUE THREAD

**Issue by nlyubova** [ros-aldebaran/nao_dcm_robot#9]
cannot find it with apt-get. should we release it or not?

**Comment by keulYSMB** [comment]
I did not release it because it's supposed to depend on the naoqiSDK which aldebaran does not release publicly. So we can release it with missing dependencies and people have to figure it out at runtime (populate LD_LIBRARY_PATH or PYTHONPATH accordingly).
So I thought that it was better not to release it but to have all the step to compile it and run it properly in a ROS Tutorial.

Then it was a personnal decision, if anybody think that it's better to release it anyway please speak up on this thread.

**Comment by vrabaud** [comment]
It requires the NAOqi SDK to compile, so we cannot release it.
What you can do is change the code to use libqi instead of the SDK and that will compile, just like we are doing with naoqi_driver.
